write-host "In iisConfigurationPSV5"
Set-ExecutionPolicy Bypass -Scope Process

Enable-WindowsOptionalFeature -Online -FeatureName IIS-WebServerRole                          
Enable-WindowsOptionalFeature -Online -FeatureName IIS-WebServer                              
Enable-WindowsOptionalFeature -Online -FeatureName IIS-CommonHttpFeatures                     
Enable-WindowsOptionalFeature -Online -FeatureName IIS-HttpErrors                             
Enable-WindowsOptionalFeature -Online -FeatureName IIS-ApplicationDevelopment                 
Enable-WindowsOptionalFeature -Online -FeatureName IIS-NetFxExtensibility                     
Enable-WindowsOptionalFeature -Online -FeatureName IIS-NetFxExtensibility45                   
Enable-WindowsOptionalFeature -Online -FeatureName IIS-HealthAndDiagnostics                   
Enable-WindowsOptionalFeature -Online -FeatureName IIS-HttpLogging                            
Enable-WindowsOptionalFeature -Online -FeatureName IIS-Security                               
Enable-WindowsOptionalFeature -Online -FeatureName IIS-RequestFiltering                       
Enable-WindowsOptionalFeature -Online -FeatureName IIS-Performance                            
Enable-WindowsOptionalFeature -Online -FeatureName IIS-WebServerManagementTools    
Enable-WindowsOptionalFeature -Online -FeatureName IIS-StaticContent                          
Enable-WindowsOptionalFeature -Online -FeatureName IIS-DefaultDocument                        
Enable-WindowsOptionalFeature -Online -FeatureName IIS-DirectoryBrowsing                      
Enable-WindowsOptionalFeature -Online -FeatureName IIS-WebSockets                             
Enable-WindowsOptionalFeature -Online -FeatureName IIS-ApplicationInit                                                       
Enable-WindowsOptionalFeature -Online -FeatureName IIS-ISAPIExtensions                        
Enable-WindowsOptionalFeature -Online -FeatureName IIS-ISAPIFilter                            
Enable-WindowsOptionalFeature -Online -FeatureName IIS-ServerSideIncludes                     
Enable-WindowsOptionalFeature -Online -FeatureName IIS-CustomLogging                          
Enable-WindowsOptionalFeature -Online -FeatureName IIS-BasicAuthentication                    
Enable-WindowsOptionalFeature -Online -FeatureName IIS-HttpCompressionStatic                  
Enable-WindowsOptionalFeature -Online -FeatureName IIS-ManagementConsole                      
Enable-WindowsOptionalFeature -Online -FeatureName IIS-ODBCLogging 
Enable-WindowsOptionalFeature -Online -FeatureName IIS-ASPNET                                 
Enable-WindowsOptionalFeature -Online -FeatureName IIS-ASPNET45 
